export const GET_ERRORS = "GET_ERRORS";
export const GET_PROJECTS = "GET_PROJECTS";
export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const GET_DEMANDE = "GET_DEMANDE";
export const DELETE_DEMANDE = "DELETE_DEMANDE";
export const FETCH_DEMANDE = "FETCH_DEMANDE";
export const FETCH_DEMANDE_NUMERO_COMPTE = "FETCH_DEMANDE_NUMERO_COMPTE";
